
roasts = [
    # Original roasts
    "Even a broken clock is right twice a day, but {} manages to be wrong 24/7 😂",
    "I'd roast {}, but my mom said I'm not allowed to burn trash 🔥",
    "{} is like a cloud - when they disappear it's a beautiful day ☁️",
    "I'd tell {} a joke but they're already living one 🎭",
    "If laughter is the best medicine, {}'s face must be curing the world 🌍",
    "{} has a face for radio and a voice for silent movies 🎬",
    "{} is so slow, they got outrun by a statue 🏃",
    "I'd agree with {} but then we'd both be wrong 🤷",
    "Hey {}, you're like homework - too hard and not worth doing 📚",
    "{} is proof that evolution can go in reverse 🦍",
    # New roasts
    "{} is like a Monday - nobody likes you 📅",
    "I bet {}'s parents still ask if it's too late for adoption 👶",
    "{} is so basic, they raise the pH level of any room they enter 🧪",
    "They say everyone has a purpose in life, {}'s is to serve as a warning to others ⚠️",
    "{} is living proof that you can live without a brain 🧠",
    "I'm not saying {} is dumb, but they got hit by a parked car 🚗",
    "{} is like expired milk - nobody wants you and you smell funny 🥛",
    "I'd say {} is a joke, but jokes have meaning 🎯",
    "{} is so slow, Internet Explorer feels bad for them 💻",
    "{} is so dense, light bends around them 💫",
    "If {} was a spice, they'd be flour 🌾",
    "{} is so boring, watching paint dry filed a complaint 🎨",
    "I would roast {}, but nature already did its worst 🌋",
    "Hey {}, you remind me of the ocean - salty and full of trash 🌊",
    "{} is like a selfie - fake and needs filters to look good 📱",
    "{} has the personality of a wet sock 🧦",
    "I bet {} claps when the plane lands ✈️",
    "{} is so annoying, Spotify starts playing ads voluntarily 🎵",
    "When {} enters a room, all the balloons deflate 🎈",
    "{}'s family tree must be a cactus because everyone's a prick 🌵",
    "{} is so clueless, they got lost in a one-room house 🏠",
    "Hey {}, did you fall from heaven? Because your face looks like it hit concrete 😇",
    "{} is like a cloud in gaming - high ping and low performance ☁️",
    "{}'s idea of dressing up is putting on matching socks 👔",
    "{} is so extra, drama queens take notes 👑",
    "{} is like a participation trophy - nobody really wants you 🏆",
    "{}'s comebacks are like Internet Explorer - slow and outdated 🌐",
    "I'd roast {}, but my oven isn't big enough 🔥",
    "{} is so old, their memory is in black and white 📺",
    "{} is about as useful as a screen door on a submarine 🚢",
    "{} has a face that only a mother could love... blindfolded 👩‍👦",
    "{} is so unoriginal, they plagiarize their own personality 📝",
    "{}'s brain is like a broken calculator - lots of numbers but wrong answers 🧮",
    "If {} was a book, they'd be the terms and conditions 📖",
    "{} is so cold, penguins are filing complaints 🐧",
    "{} is like a broken pencil - pointless 📏",
    "{} has the charm of a brick wall and half the personality 🧱",
    "{} is so basic, they think salt is spicy 🌶️",
    "{} got lost in their own bedroom... twice 🛏️",
    "{} is like WiFi without internet - no connection 📡"
]

facts = [
    # Original facts
    "Fun fact: {} probably didn't know that honey never spoils 🍯",
    "Hey {}, did you know that cows have best friends? Unlike you 🐮",
    "Interesting fact for {}: Bananas are berries but strawberries aren't 🍌",
    "{} might be interested to know that sloths are faster swimmers than they are climbers... just like their career progress 🦥",
    "Tell {}: Penguins propose with pebbles. Still more romantic than them 🐧",
    "Fun fact for {}: Space smells like burnt steak. Speaking of space, that's what everyone needs from you 🚀",
    "{} should know that octopuses have three hearts. That's three more than them 🐙",
    "Hey {}, dolphins give each other names. They'd probably call you 'mistake' 🐬",
    "Tell {}: A day on Venus is longer than its year. Like their bathroom breaks 💫",
    "Scientific fact for {}: The human body contains enough carbon to make 900 pencils. Finally, they're worth something! ✏️",
    # New facts
    "Hey {}, giraffes can clean their ears with their tongue - they'd still refuse to listen to you 🦒",
    "{} should know that snails can sleep for 3 years - just like their social life 🐌",
    "Fun fact: A crocodile can't stick its tongue out, {} can't keep theirs in 🐊",
    "Tell {}: Honeybees can recognize human faces - but they still can't remember yours 🐝",
    "{} might find it interesting that cats can't taste sweetness - like their personality 😺",
    "Hey {}, butterflies taste with their feet - still better taste than your fashion choices 🦋",
    "Did you know, {}, that ostriches have eyes bigger than their brains? Reminds me of you 🦅",
    "{}, hippos secrete pink sweat - more interesting than your conversations 🦛",
    "Fun fact for {}: Sloths take two weeks to digest food - faster than you process simple jokes 🦥",
    "Hey {}, kangaroos can't walk backwards - like your personal development 🦘",
    "{} should know that elephants are the only mammals that can't jump - like your career 🐘",
    "Tell {}: A woodpecker's tongue wraps around its brain - more flexibility than your thinking 🐦",
    "Hey {}, platypuses glow under UV light - unlike your future 🦆",
    "{}, koalas have fingerprints like humans - but at least they're useful 🐨",
    "Did you know, {}, that turtles can breathe through their butts? Still more elegant than your speaking 🐢",
    "Fun fact: Sharks existed before trees - like {}'s outdated jokes 🦈",
    "{}, flamingos aren't naturally pink - like your fake personality 🦩",
    "Hey {}, crows can remember human faces - but they choose to forget yours 🦅",
    "Tell {}: Zebras have unique stripes - unlike their basic character 🦓",
    "{} might find it interesting that jellyfish have survived 650 million years - longer than your relationships 🎐",
    "Fun fact for {}: Hummingbirds can fly backwards - unlike your progress in life 🐦",
    "Hey {}, penguins mate for life - something you'll never experience 🐧",
    "{}, gorillas can catch human colds - but even they avoid you 🦍",
    "Did you know, {}, that bees never sleep? Like your attempts to be cool 🐝",
    "Tell {}: Pigeons can do math - better than you 🐦",
    "Hey {}, octopuses have blue blood - still warmer than your heart 🐙",
    "{}, chameleons don't change color to match backgrounds - unlike your personality 🦎",
    "Fun fact: Starfish don't have brains - remind you of someone? ⭐",
    "{} should know that rabbits can't vomit - but they would if they met you 🐰",
    "Tell {}: Polar bears are left-handed - more interesting than your stories 🐻‍❄️",
    "Hey {}, a snail can sleep for 3 years - like your motivation 🐌",
    "{}, hippos can run faster than humans - like everyone running from you 🦛",
    "Fun fact: Owls can't move their eyes - they just roll them at {} 🦉",
    "Tell {}: Goats have rectangular pupils - still less strange than your selfies 🐐",
    "{} might like to know that lobsters are immortal - unlike their social life 🦞",
    "Hey {}, tigers have striped skin, not just fur - deeper than your personality 🐯",
    "{}, elephants are the only animals that can't jump - like your achievements 🐘",
    "Fun fact: Dolphins sleep with one eye open - to watch out for {} 🐬",
    "Tell {}: Ants never sleep - like their conscience 🐜",
    "Hey {}, giraffes have the same number of vertebrae as humans - but stand much taller 🦒"
]

pickup_lines = [
    # Original pickup lines
    "Hey {}, are you a parking ticket? Because you've got FINE written all over you 🎫",
    "{}, did it hurt when you fell from the vending machine? Cause you're a snack 🍫",
    "Are you French, {}? Because Eiffel for you 🗼",
    "{}, are you a cat? Because you're purr-fect 🐱",
    "Hey {}, are you a bank loan? Because you've got my interest 💰",
    "{}, do you have a map? I keep getting lost in your eyes 🗺️",
    "Are you a campfire, {}? Because you are hot and I want s'more 🔥",
    "{}, are you made of copper and tellurium? Because you're Cu-Te 🧪",
    "Hey {}, are you a camera? Because every time I look at you, I smile 📸",
    "I was feeling a bit off today {}, but you definitely turned me on 💫",
    # New pickup lines
    "Hey {}, are you WiFi? Because I'm feeling a strong connection 📶",
    "{}, are you a dictionary? Because you add meaning to my life 📚",
    "Is your name Google, {}? Because you've got everything I've been searching for 🔍",
    "{}, are you a charged particle? Because I'm attracted to you ⚡",
    "Hey {}, is your dad a baker? Because you're a cutie pie 🥧",
    "{}, are you a magician? Because whenever I look at you, everyone else disappears 🎩",
    "Are you a time traveler, {}? Because I see you in my future 🕰️",
    "{}, are you made of dark matter? Because you're invisible to everyone but me 🌌",
    "Hey {}, are you a keyboard? Because you're just my type ⌨️",
    "Are you a compiler error, {}? Because you've got me stuck on you 💻",
    "{}, are you a star? Because I can't stop orbiting around you 🌟",
    "Hey {}, are you a DNA helix? Because we'd make a perfect pair 🧬",
    "{}, are you a battery? Because you energize my life 🔋",
    "Are you a rainbow, {}? Because you brighten up my day 🌈",
    "Hey {}, are you a library book? Because I can't help checking you out 📖",
    "{}, are you a star? Because I've been wishing for someone like you ⭐",
    "Are you a programmer, {}? Because you've got my heart coding for you 💘",
    "{}, are you gravity? Because I keep falling for you 🪂",
    "Hey {}, are you a song? Because you're music to my ears 🎵",
    "Are you a calculator, {}? Because you make the numbers in my head add up 🧮",
    "{}, are you made of beryllium, gold, and titanium? Because you are BeAuTi-ful 💎",
    "Hey {}, are you a constellation? Because you're a star in my sky 🌠",
    "{}, are you a chocolate cake? Because you're sweet and tempting 🍫",
    "Are you a magnet, {}? Because you've got me attracted 🧲",
    "Hey {}, are you a sunflower? Because you light up my world 🌻",
    "{}, are you a puzzle? Because I'm trying to figure you out 🧩",
    "Are you a meteor, {}? Because you've made an impact on me ☄️",
    "{}, are you a gardener? Because you've planted yourself in my heart 🌱",
    "Hey {}, are you a snowflake? Because you're one of a kind ❄️",
    "Are you a painter, {}? Because you color my world 🎨",
    "{}, are you a detective? Because you've been investigating my heart 🔍",
    "Hey {}, are you a bookmark? Because I've been looking for you in every story 📚",
    "{}, are you a compass? Because you guide my heart ⭐",
    "Are you a chef, {}? Because you've got all the ingredients I need 👨‍🍳",
    "Hey {}, are you a cloud? Because you bring sunshine to my life ☁️",
    "{}, are you an artist? Because you draw my attention 🎨",
    "Are you a dream, {}? Because you're too good to be true 💭",
    "{}, are you a pilot? Because you make my heart soar ✈️",
    "Hey {}, are you a musician? Because we make perfect harmony 🎵",
    "Are you a wizard, {}? Because you've cast a spell on me 🧙‍♂️"
]
